create database bookstoredb;
use bookstoredb;


create table COUNTRY (
COUNTRY_ID INT PRIMARY KEY auto_increment,
COUNTRY_NAME varchar(20) NOT null
);

create table ADDRESS_STATUS (
STATUS_ID INT PRIMARY KEY auto_increment,
STATUS_NAME varchar(20) NOT null
);

create table PUBLISHER (
PUBLISHER_ID INT PRIMARY KEY auto_increment,
PUBLISHER_NAME varchar(200) not null
);


create table BOOK_LANGUAGE (
LANGUAGE_ID INT PRIMARY KEY auto_increment,
LANGUAGE_NAME varchar(200) NOT NULL
);


create table AUTHOR (
AUTHOR_ID INT PRIMARY KEY auto_increment,
AUTHOR_NAME varchar(100) NOT null
);


create table BOOKS (
BOOK_ID int primary key auto_increment,
TITLE varchar (200) not null,
ISBN VARCHAR (200),
PUBLISHER_ID INT,
LANGUAGE_ID INT,
PRICE DECIMAL (10, 2),
FOREIGN KEY (PUBLISHER_ID) REFERENCES PUBLISHER (PUBLISHER_ID),
FOREIGN KEY (LANGUAGE_ID) REFERENCES BOOK_LANGUAGE (LANGUAGE_ID)
);

create table BOOK_AUTHOR (
BOOK_ID INT,
AUTHOR_ID INT,
PRIMARY KEY (BOOK_ID, AUTHOR_ID),
FOREIGN KEY (BOOK_ID) REFERENCES BOOKS(BOOK_ID),
FOREIGN KEY (AUTHOR_ID) REFERENCES AUTHOR(AUTHOR_ID)
);


CREATE TABLE CUSTOMER (
    CUSTOMER_ID INT PRIMARY KEY AUTO_INCREMENT,
    CUSTOMER_NAME VARCHAR(200) NOT NULL
);

CREATE TABLE ADDRESS (
    ADDRESS_ID INT PRIMARY KEY AUTO_INCREMENT,
    STREET_ADDRESS VARCHAR(255) NOT NULL,
    CITY VARCHAR(100) NOT NULL,
    STATE VARCHAR(100),
    POSTAL_CODE VARCHAR(20),
    COUNTRY_ID INT,
    FOREIGN KEY (COUNTRY_ID) REFERENCES COUNTRY(COUNTRY_ID)
);

CREATE TABLE CUSTOMER_ADDRESS (
    CUSTOMER_ID INT,
    ADDRESS_ID INT,
    STATUS_ID INT,
    PRIMARY KEY (CUSTOMER_ID, ADDRESS_ID),
    FOREIGN KEY (CUSTOMER_ID) REFERENCES CUSTOMER(CUSTOMER_ID),
    FOREIGN KEY (ADDRESS_ID) REFERENCES ADDRESS(ADDRESS_ID),
    FOREIGN KEY (STATUS_ID) REFERENCES ADDRESS_STATUS(STATUS_ID)
);


CREATE TABLE ORDER_STATUS (
    STATUS_ID INT PRIMARY KEY AUTO_INCREMENT,
    STATUS_NAME VARCHAR(100) NOT NULL
);

CREATE TABLE SHIPPING_METHOD (
    SHIPPING_METHOD_ID INT PRIMARY KEY AUTO_INCREMENT,
    METHOD_NAME VARCHAR(100) NOT NULL
);
CREATE TABLE CUST_ORDER (
    ORDER_ID INT PRIMARY KEY AUTO_INCREMENT,
    CUSTOMER_ID INT,
    ORDER_DATE DATE NOT NULL,
    ORDER_STATUS VARCHAR(50),
    SHIPPING_METHOD_ID INT,
    FOREIGN KEY (CUSTOMER_ID) REFERENCES CUSTOMER(CUSTOMER_ID),
    FOREIGN KEY (SHIPPING_METHOD_ID) REFERENCES SHIPPING_METHOD(SHIPPING_METHOD_ID)
    );


CREATE TABLE ORDER_LINE (
    ORDER_LINE_ID INT PRIMARY KEY AUTO_INCREMENT,
    ORDER_ID INT,
    BOOK_ID INT,
    QUANTITY INT,
    PRICE DECIMAL(10, 2),
    FOREIGN KEY (ORDER_ID) REFERENCES CUST_ORDER(ORDER_ID),
    FOREIGN KEY (BOOK_ID) REFERENCES BOOKS(BOOK_ID)
);

CREATE TABLE ORDER_HISTORY (
    HISTORY_ID INT PRIMARY KEY AUTO_INCREMENT,
    ORDER_ID INT,
    STATUS VARCHAR(100),
    CHANGE_DATE DATE NOT NULL,
    FOREIGN KEY (ORDER_ID) REFERENCES CUST_ORDER(ORDER_ID)
);



CREATE TABLE BOOKS (
    BOOK_ID INT PRIMARY KEY AUTO_INCREMENT,
    TITLE VARCHAR(200) NOT NULL,
    ISBN VARCHAR(200),
    PUBLISHER_ID INT,
    LANGUAGE_ID INT,
    PRICE DECIMAL(10, 2),
    FOREIGN KEY (PUBLISHER_ID) REFERENCES PUBLISHER(PUBLISHER_ID),
    FOREIGN KEY (LANGUAGE_ID) REFERENCES BOOK_LANGUAGE(LANGUAGE_ID)
);





